### ISSUE TITLE
Container failing if started with links

### ISSUE THREAD

**Issue by omata-metamax** [QuantumObject/docker-alpine#4]
Hello,

Recently I did build some images based on yours and if I start it issuing a simple:

```bash
docker run --name my-image -d -P myimage:1.0.0
```

It works fawlessly, but If I use compose or even a command, but using links with that image it fails at the startup.

The error is originated at `my_init` file where when is exporting environment vaiables it fails with the following error:

```
export eval MYSQL_ENV_GPG_KEYS=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
/sbin/my_init: export: line 1: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX: bad variable name
```
_BTW: The failing environment variable is the injected one from the linked container._

I'm guessing that something changed at **docker daemon** that is avoiding the script to do it's job as it's designed. So, since I'm not a `sh` gurú, I'm posting this issue here because I guess that a validation into the script could be done to fix the issue.

**Docker info**

```
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 45
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /home/user/docker-data/aufs
 Backing Filesystem: extfs
 Dirs: 56
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-77-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 5.72GiB
Name: workstation
ID: ...
Docker Root Dir: /home/user/docker-data
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

If you need any other information, please let me know.

**Comment by omata-metamax** [comment]
I did some tests linking it to another container without MySQL service and that specific variable with the PGP key as value and it started flawlessly. So I guess that the issue is related with the value into that file; two strings separated by a space.

**Comment by omata** [comment]
Over some other tests, there is a spot where any injected variable fails. :(

**Comment by angelrr7702** [comment]
It appear that the problem is when a variable is assigned two or more values ..

**Comment by omata** [comment]
You are right. I remove that variable with two values and it complains on another one that contains: `*.local, 169.254/16`

Do you know why it is happening?

Thank you for your reply.

**Comment by angelrr7702** [comment]
Hi,
 please try quantumobject/docker-alpine:test2  to check if work with both cases ... I remove the variable management from the my init script . When I wrote initial the code in sh the reason was not to increase size of container by using python or other package  but I didn't realize that variable can have more that one value . I try to fix it but it broke in other areas at the script .. 

sincerely
Angel Rodriguez

**Comment by omata-metamax** [comment]
I will check that, thank you!!!!

**Comment by omata-metamax** [comment]
¿Hablas español?

**Comment by omata-metamax** [comment]
Until now my images are woking with the new script, but I need to do more tests. Can you explain to me what is doing your code that handle the environment variables? these are just for create the files with envs, _(json and sh files)_, or does other things? I'm not versed on shell scripting.

And thanks for your effort.

**Comment by angelrr7702** [comment]
This container and the other docker-baseimage (ubuntu) was originally base on https://github.com/phusion/baseimage-docker  but I replace python by sh (plus other changes) to reduce size of the container .. the idea is to have a container that can be run different process inside .. (opposite of the way Docker recommended --one process only) , and the needed for that in my case was that I want to deploy different open source software by container to help people to test / learn about them .. and easier way to installed www.quantumobject.org .. but no for final deployment . When the original open source project organization produce their own container I planning to remove mine from Docker repository . the idea of environment variables manipulation was original from phusion   but maybe will be better to used the already existing Dockerfile command to pass it to the container .. or by -e at run command . It have other uses but I almost never used it .. and docker from the original have been chnage a lot ..

**Comment by omata-metamax** [comment]
I got it fixed,

file: `/sbin/my_init`

```bash
:22 export eval $FILE=`cat $file`
```

by

```bash
:22 set $FILE=`cat $file`
:23 export env $FILE
```
It is working again.

**Comment by omata-metamax** [comment]
I got it fixed,

file: `/sbin/my_init`

```bash
:22 export eval $FILE=`cat $file`
```

by

```bash
:22 set $FILE=`cat $file`
:23 export eval $FILE
```
It is working again.

**Comment by angelrr7702** [comment]
thanks

**Comment by omata-metamax** [comment]
You are welcome!!!
