### ISSUE TITLE
What's the meaning of options -f and -d of /usr/sbin/crond

### ISSUE THREAD

**Issue by gentcys** [QuantumObject/docker-alpine#5]
https://github.com/tomxiong/docker-alpine/blob/b49ba30825b61442690c6dd0f9892b0fea48fa2b/runit/cron#L3 #2 

`exec /usr/sbin/crond -f -d 0`

**Comment by angelrr7702** [comment]
-f for "foreground"
-d N    Set log level, log to stderr

**Comment by gentcys** [comment]
Thanks.
